-- MySQL Script generated by MySQL Workbench
-- Sat 08 Apr 2017 02:33:52 PM EDT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema ulbora_challenge_test
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ulbora_challenge_test
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ulbora_challenge_test` DEFAULT CHARACTER SET utf8 ;
USE `ulbora_challenge_test` ;

-- -----------------------------------------------------
-- Table `ulbora_challenge_test`.`language`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ulbora_challenge_test`.`language` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ulbora_challenge_test`.`captcha_not`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ulbora_challenge_test`.`captcha_not` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `question` VARCHAR(300) NULL,
  `answer` VARCHAR(20) NULL,
  `language_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_captcha_not_language_idx` (`language_id` ASC),
  CONSTRAINT `fk_captcha_not_language`
    FOREIGN KEY (`language_id`)
    REFERENCES `ulbora_challenge_test`.`language` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
